apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  namespace: dfash
spec:
  selector:
    matchLabels:
      app: flask
  replicas: 3
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: restavratof/flask-image:fib
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: dfash
spec:
  ports:
  - port: 80
    targetPort: 80
    name: http
  selector:
    app: flask
