---
apiVersion: v1
kind: Service
metadata:
  name: df-app
  namespace: dfash
  labels:
    app: df-app
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 5000
    protocol: TCP
    targetPort: http
  selector:
    app: df-app