apiVersion: apps/v1
kind: Deployment
metadata:
  name: express
  namespace: demo
spec:
  selector:
    matchLabels:
      app: express
  template:
    metadata:
      labels:
        app: express
    spec:
      containers:
      - image: restavratof/flask-image:gunicorn
        name: express
        ports:
        - name: http
          containerPort: 5000
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 200m
            memory: 128Mi
