---
apiVersion: v1
kind: Service
metadata:
  name: df1
  namespace: df-demo
  labels:
    app: df1
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 5000
    protocol: TCP
    targetPort: http
  selector:
    app: df1
