---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: df1
  namespace: df-demo
  labels:
    team: devops
spec:
  endpoints:
  - port: http
    interval: 15s
  namespaceSelector:
    matchNames:
    - df-demo
  selector:
    matchLabels:
      app: df1
